# Generated by Django 5.2.17 on 2026-10-01 14:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=300)),
                ("url_key", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("default_branch", models.CharField(max_length=255)),
                ("commit_sha", models.CharField(max_length=40)),
                ("private", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("ingesting", "Ingesting"),
                            ("waiting_for_model", "Waiting for model"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("languages", models.JSONField(blank=True, default=dict)),
                ("frameworks", models.JSONField(blank=True, default=list)),
                ("detection", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "repositories",
                "indexes": [models.Index(fields=["status"], name="repo_status_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("url_key", "commit_sha"), name="uniq_repo_commit"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("waiting_for_model", "Waiting for model"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("steps", models.JSONField(blank=True, default=list)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_jobs",
                "indexes": [
                    models.Index(fields=["repository", "-created_at"], name="job_repo_recent_idx"),
                    models.Index(fields=["status"], name="job_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRepository",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="repos.repository"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_repos",
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="user_repo_recent_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "repository"), name="uniq_user_repo")
                ],
            },
        ),
    ]
