# Generated by Django 5.2.17 on 2026-10-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrepository",
            name="access_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
