# Generated by Django 5.2.17 on 2026-10-01 15:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("waiting_for_model", "Waiting for model"),
                            ("done", "Done"),
                            ("partial", "Partially done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=200)),
                ("sections", models.JSONField(blank=True, default=dict)),
                ("checkpoint", models.JSONField(blank=True, null=True)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("est_cost", models.FloatField(default=0.0)),
                ("error", models.TextField(blank=True, default="")),
                ("waiting_since", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "db_table": "analyses",
                "indexes": [models.Index(fields=["status"], name="analysis_status_idx")],
            },
        ),
    ]
